name = "retryly-web-pixel"
uid = "ddd543ab-0ae8-3cd0-4c07-9ae9cefca2691d6719a8"
type = "web_pixel_extension"
runtime_context = "strict"

[settings]
type = "object"

[settings.fields.endpoint]
name = "Tracking endpoint"
type = "single_line_text_field"

[settings.fields.shopDomain]
name = "Shop domain"
type = "single_line_text_field"
